apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: v2-mlflow-elasticnet-wine
  namespace: seldon
spec:
  protocol: v2
  predictors:
  - name: default
    replicas: 1
    graph:
      name: classifier
      implementation: MLFLOW_SERVER
      modelUri: gs://seldon-models/v1.14.1/mlflow/elasticnet_wine
      envSecretRefName: minio-bucket
      logger:
        mode: all
