apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: v2-income-explainer
  namespace: seldon
spec:
  protocol: v2
  predictors:
  - name: default
    replicas: 1
    graph:
      name: classifier
      implementation: SKLEARN_SERVER
      modelUri: gs://seldon-models/scv2/examples/income/classifier
      logger:
        mode: all
    explainer:
      type: AnchorTabular
      modelUri: gs://seldon-models/scv2/examples/income/explainer
